version: "2"
services:
  kafka:
    container_name: kafka-cluster-live
    image: ucamcldtg/kafka-cluster
    restart: always
    logging:
      driver: journald
      options:
        tag: kafka
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /local/data/kafka-live:/kafka-data:rw
      - ./server.properties.template:/opt/kafka/config/server.properties.template:ro
      - ./log4j.properties:/opt/kafka/config/log4j.properties:ro
    environment:
      KAFKA_HEAP_OPTS: "-Xmx2G -Xms2G"      
networks:
  default:
    external:
      name: isaac
